### ISSUE TITLE
Create Frontend Draft

### ISSUE THREAD

**Issue by Konstantinov-Innokentii** [Konstantinov-Innokentii/ideal-sniffle#8]
Feel free to inspire by Toggl :)

**Comment by Konstantinov-Innokentii** [comment]
After cloning repo run `docker-compose up -d --build` and create .env.dev file 
```
SECRET_KEY=<Insert Secret Key>
DEBUG=True
SQL_ENGINE=django.db.backends.postgresql
SQL_DATABASE=tracker
SQL_USER=user
SQL_PASSWORD=qwerty
SQL_HOST=db
SQL_PORT=5432
```
Explore endpoints in browsable api at `api/v1/`

**Comment by RomanChumakov** [comment]
Is need satisfy some requirements for the SECRET_KEY parameter? I try to run project with:
python3 manage.py runserver
and got the error:
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty
Venv is activated and key is added.

**Comment by Konstantinov-Innokentii** [comment]
- [ ] task form

- [ ] tasks list

- [ ] task related time entries list
